# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Kg_TitanicNB',
                'doc_host': 'https://Positron00.github.io',
                'git_url': 'https://github.com/Positron00/Kg_TitanicNB',
                'lib_path': 'Kg_TitanicNB'},
  'syms': { 'Kg_TitanicNB.core': { 'Kg_TitanicNB.core.foo': ('core.html#foo', 'Kg_TitanicNB/core.py'),
                                   'Kg_TitanicNB.core.say_hello': ('core.html#say_hello', 'Kg_TitanicNB/core.py')},
            'Kg_TitanicNB.titanic_checkData': { 'Kg_TitanicNB.titanic_checkData.impute_age': ( 'titanicdataset.html#impute_age',
                                                                                               'Kg_TitanicNB/titanic_checkData.py'),
                                                'Kg_TitanicNB.titanic_checkData.impute_fare': ( 'titanicdataset.html#impute_fare',
                                                                                                'Kg_TitanicNB/titanic_checkData.py')}}}
