wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1709149068.307929
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.12
      5: 0.16.3
      8:
      - 2
      - 5
      - 9
      - 13
      13: darwin-x86_64
